function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 12-Oct-2024 16:13:32

% Create figure
figure('WindowState','maximized');

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'DisplayName','data1');
set(plot1(2),'DisplayName','data2');

% Create ylabel
ylabel('Utsignal');

% Create xlabel
xlabel('Tid (s)');

% Create title
title('Stegsvar för det slutna systemet');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Create legend
legend(axes1,'show');

